spring:
  application:
    name: order-service
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5437/orderdb
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 2s
          multiplier: 2.0
          max-interval: 10s
          max-attempts: 5
        default-requeue-rejected: false

server:
  port: 8086
  servlet:
    context-path: /api/

application:
  client:
    user:
      url: http://localhost:8083/api/v1/users
    inventory:
      url: http://localhost:8085/api/v1/products
